export const CARDS = [
  {
    id: 1, bank: "shinhan", bankName: "신한카드", name: "Deep Dream", type: "credit",
    fee: { domestic: 20000, intl: 30000 },
    categories: ["쇼핑", "식음료", "교통"],
    benefits: [
      { icon: "🛍", text: "백화점/마트 5% 할인" },
      { icon: "🚇", text: "대중교통 10% 할인" },
      { icon: "☕", text: "스타벅스 30% 할인" },
    ],
    tags: ["스타벅스", "백화점", "대중교통", "신세계"],
    rating: 4.1, minSpend: 300000, maxDiscount: 30000,
  },
  {
    id: 2, bank: "kb", bankName: "KB국민카드", name: "탄탄대로 티타늄", type: "credit",
    fee: { domestic: 15000, intl: 20000 },
    categories: ["주유", "교통", "통신"],
    benefits: [
      { icon: "⛽", text: "주유 리터당 60원 할인" },
      { icon: "📱", text: "통신요금 월 5,000원 할인" },
      { icon: "🚗", text: "하이패스 10% 적립" },
    ],
    tags: ["주유", "통신", "고속도로", "GS칼텍스"],
    rating: 4.0, minSpend: 400000, maxDiscount: 20000,
  },
  {
    id: 3, bank: "hyundai", bankName: "현대카드", name: "M Edition3", type: "credit",
    fee: { domestic: 20000, intl: 30000 },
    categories: ["쇼핑", "여행"],
    benefits: [
      { icon: "✈️", text: "해외 결제 포인트 2배 적립" },
      { icon: "🛒", text: "현대백화점 10% 할인" },
      { icon: "🏨", text: "호텔스닷컴 5% 추가 할인" },
    ],
    tags: ["여행", "해외", "현대백화점", "호텔"],
    rating: 4.5, minSpend: 500000, maxDiscount: 50000,
  },
  {
    id: 4, bank: "samsung", bankName: "삼성카드", name: "삼성카드 7 V2", type: "credit",
    fee: { domestic: 0, intl: 0 },
    categories: ["쇼핑", "식음료"],
    benefits: [
      { icon: "💳", text: "삼성페이 결제 0.5% 캐시백" },
      { icon: "🍽️", text: "음식점 1% 적립" },
      { icon: "🛍", text: "쿠팡 2% 할인" },
    ],
    tags: ["무연회비", "삼성페이", "쿠팡", "음식점"],
    rating: 3.7, minSpend: 200000, maxDiscount: 15000,
  },
  {
    id: 5, bank: "lotte", bankName: "롯데카드", name: "LOCA 365", type: "credit",
    fee: { domestic: 30000, intl: 40000 },
    categories: ["쇼핑", "여행", "식음료"],
    benefits: [
      { icon: "🏪", text: "롯데마트/백화점 7% 할인" },
      { icon: "✈️", text: "항공 마일리지 2배 적립" },
      { icon: "🎬", text: "롯데시네마 4,000원 할인" },
    ],
    tags: ["롯데", "마일리지", "영화", "면세점"],
    rating: 3.9, minSpend: 600000, maxDiscount: 60000,
  },
  {
    id: 6, bank: "woori", bankName: "우리카드", name: "카드의 정석 EVERY", type: "credit",
    fee: { domestic: 0, intl: 0 },
    categories: ["식음료", "교통", "통신"],
    benefits: [
      { icon: "🍔", text: "편의점/카페 10% 할인" },
      { icon: "🚌", text: "버스/지하철 월 5,000원 한도" },
      { icon: "📺", text: "구독 서비스 5% 할인" },
    ],
    tags: ["무연회비", "편의점", "구독", "대중교통"],
    rating: 4.2, minSpend: 300000, maxDiscount: 15000,
  },
  {
    id: 7, bank: "shinhan", bankName: "신한카드", name: "S-Line 체크", type: "check",
    fee: { domestic: 0, intl: 0 },
    categories: ["식음료", "교통", "쇼핑"],
    benefits: [
      { icon: "🏪", text: "편의점 5% 할인" },
      { icon: "🚇", text: "교통 월 3,000원 한도" },
      { icon: "☕", text: "카페 3% 적립" },
    ],
    tags: ["체크", "무연회비", "편의점", "카페"],
    rating: 3.5, minSpend: 0, maxDiscount: 10000,
  },
  {
    id: 8, bank: "kb", bankName: "KB국민카드", name: "알파원 체크", type: "check",
    fee: { domestic: 0, intl: 0 },
    categories: ["쇼핑", "식음료"],
    benefits: [
      { icon: "🛍", text: "온라인 쇼핑 1.5% 적립" },
      { icon: "🍽️", text: "음식점 1% 적립" },
      { icon: "💰", text: "전월 실적 무관 기본 0.5% 적립" },
    ],
    tags: ["체크", "무연회비", "온라인쇼핑", "실적무관"],
    rating: 4.0, minSpend: 0, maxDiscount: 10000,
  },
  {
    id: 9, bank: "hana", bankName: "하나카드", name: "비바G 체크", type: "check",
    fee: { domestic: 0, intl: 0 },
    categories: ["주유", "교통"],
    benefits: [
      { icon: "⛽", text: "주유 리터당 30원 할인" },
      { icon: "🚌", text: "버스/지하철 5% 할인" },
      { icon: "🅿️", text: "주차 월 1회 무료" },
    ],
    tags: ["체크", "주유", "교통", "무연회비"],
    rating: 3.6, minSpend: 0, maxDiscount: 8000,
  },
];
